### ISSUE TITLE
mobile: email links too far left

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/park-grants-en#10]
The email address links are running off the screen on mobile. Perhaps switch to left alignment or change font size?
![Screenshot_20200113-162550](https://user-images.githubusercontent.com/46387723/72293645-f1fe0a80-3621-11ea-8498-d020e92389ed.png)

**Comment by hubret** [comment]
the font is already kind of small. the problem is that in the backend there are nonbreaking spaces before and after "or contact" and its making it not wrap. but wrapping also looks ugly
![image](https://user-images.githubusercontent.com/8590448/72355930-5a96c700-36b6-11ea-95be-6a7bfeea517b.png)
so maybe add a line break before "or contact"

**Comment by attentioneering** [comment]
I tested it out and it kinda looks worse...
![Screenshot_20200114-102650](https://user-images.githubusercontent.com/46387723/72357220-992d8100-36b8-11ea-9308-13dfcbd1f04e.png)

**Comment by hubret** [comment]
N/A to phase 3
